/ installrc: proceed if existing file is not already a symlink
otherwise we crash when changing something to a symlink that isn't
already one, upon comparison to see if the link changed, the readlink
call fails since it's not a link

    $ installrc --test
    testmode install in '/home/scott/' with '/home/scott/.xorg/*' (y/n)? y
    testmode: ~/.Xkeymap -> .xorg/xkeymap
    testmode: ~/.Xresources -> .xorg/xresources (skipped)
    Traceback (most recent call last):
      File "/home/scott/bin/installrc", line 375, in <module>
        try: main()
      File "/home/scott/bin/installrc", line 347, in main
        counts = subprogram(src, dst)
      File "/home/scott/bin/installrc", line 313, in installrc
        try: same = normpath(join(dirfrom, readlink(linkfrom))) == linkto
    OSError: [Errno 22] Invalid argument: '/home/scott/.gtkrc-2.0'

this was fixed just be ignoring OSError in addition to FileNotFoundError
for when the old link doesn't even exist at all.  Since we're doing a
forcible link it will just overwrite it no matter if the old entry is a
real file or a link, so we don't have to worry about that

we do worry about other sources of OSError besides wrong filetype, but
we'll see if it happens in practice